# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.38
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        try:
            fp, pathname, description = imp.find_module('_pongclib', [dirname(__file__)])
            _mod = imp.load_module('_pongclib', fp, pathname, description)
        finally:
            if fp is not None: fp.close()
        return _mod
    _pongclib = swig_import_helper()
    del swig_import_helper
else:
    import _pongclib
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def clear_image(*args):
  return _pongclib.clear_image(*args)
clear_image = _pongclib.clear_image

def draw_line_2x(*args):
  return _pongclib.draw_line_2x(*args)
draw_line_2x = _pongclib.draw_line_2x

def draw_ellipse_2x(*args):
  return _pongclib.draw_ellipse_2x(*args)
draw_ellipse_2x = _pongclib.draw_ellipse_2x

def fill_ellipse_2x(*args):
  return _pongclib.fill_ellipse_2x(*args)
fill_ellipse_2x = _pongclib.fill_ellipse_2x

def set_3d_params(*args):
  return _pongclib.set_3d_params(*args)
set_3d_params = _pongclib.set_3d_params

def to_fixed(*args):
  return _pongclib.to_fixed(*args)
to_fixed = _pongclib.to_fixed

def project_x(*args):
  return _pongclib.project_x(*args)
project_x = _pongclib.project_x

def project_y(*args):
  return _pongclib.project_y(*args)
project_y = _pongclib.project_y

def draw_line_3d(*args):
  return _pongclib.draw_line_3d(*args)
draw_line_3d = _pongclib.draw_line_3d

def draw_rect_3d(*args):
  return _pongclib.draw_rect_3d(*args)
draw_rect_3d = _pongclib.draw_rect_3d

def draw_circle_3d(*args):
  return _pongclib.draw_circle_3d(*args)
draw_circle_3d = _pongclib.draw_circle_3d

def fill_circle_3d(*args):
  return _pongclib.fill_circle_3d(*args)
fill_circle_3d = _pongclib.fill_circle_3d

def draw_ellipse_3d(*args):
  return _pongclib.draw_ellipse_3d(*args)
draw_ellipse_3d = _pongclib.draw_ellipse_3d


